name       : newt
version    : 0.52.21
release    : 8
source     :
    - https://releases.pagure.org/newt/newt-0.52.21.tar.gz : 265eb46b55d7eaeb887fca7a1d51fe115658882dfe148164b6c49fccac5abb31
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Newt is a programming library for color text mode, widget based user interfaces
description: |
    Newt is a programming library for color text mode, widget based user interfaces.
builddeps  :
    - pkgconfig(popt)
    - pkgconfig(python3)
    - pkgconfig(slang)
setup      : |
    %configure --disable-static --with-python=python%python3_version%
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
