name       : newt
version    : 0.52.19
release    : 1
source     :
    - https://fedorahosted.org/releases/n/e/newt/newt-0.52.19.tar.gz : 08c0db56c21996af6a7cbab99491b774c6c09cef91cd9b03903c84634bff2e80
license    : GPL-2.0
component  : programming
summary    : Newt is a programming library for color text mode, widget based user interfaces.
description: |
    Newt is a programming library for color text mode, widget based user interfaces.
builddeps  :
    - pkgconfig(slang)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
