name       : newt
version    : 0.52.20
release    : 3
source     :
    - https://releases.pagure.org/newt/newt-0.52.20.tar.gz : 8d66ba6beffc3f786d4ccfee9d2b43d93484680ef8db9397a4fb70b5adbb6dbc
license    : GPL-2.0
component  : programming.library
summary    : Newt is a programming library for color text mode, widget based user interfaces.
description: |
    Newt is a programming library for color text mode, widget based user interfaces.
builddeps  :
    - pkgconfig(popt)
    - pkgconfig(slang)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
